name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Authenticate with GCP
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 3: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: macro-and-me

      # Step 4: Install dependencies and build frontend
      - name: Install and build frontend
        run: |
          cd macro-and-me
          npm ci
          npm run build

      - name: Generate app.yaml
        run: |
          echo "runtime: nodejs" > server/app.yaml
          echo "runtime_config:" >> server/app.yaml
          echo "  operating_system: 'ubuntu22'" >> server/app.yaml
          echo "  runtime_version: '20'" >> server/app.yaml
          echo "env: flex" >> server/app.yaml
          echo "entrypoint: npm start" >> server/app.yaml
          echo "env_variables:" >> server/app.yaml
          echo "  MONGO_URI: '${{ secrets.MONGO_URI }}'" >> server/app.yaml
          echo "  OPENAI_API_KEY: '${{ secrets.OPENAI_API_KEY }}'" >> server/app.yaml

      - name: Copy frontend build to server
        run: |
          cp -r macro-and-me/build server/public

      - name: Ensure staging bucket exists
        run: |
          if ! gsutil ls "gs://macro-and-me-staging/" > /dev/null 2>&1; then
            gsutil mb -p ${{ secrets.GCP_PROJECT_ID }} -l us-central1 gs://macro-and-me-staging/
          fi

      - name: Set default bucket permissions
        run: |
          gcloud storage buckets add-iam-policy-binding gs://macro-and-me-staging \
            --member="serviceAccount:${{ secrets.GCP_PROJECT_ID }}@appspot.gserviceaccount.com" \
            --role="roles/storage.admin"

      # Step 5: Deploy to App Engine
      - name: Deploy to App Engine
        run: |
          cd server
          ls
          npm ci
          gcloud app deploy --quiet
