name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Authenticate with GCP
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 3: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: macro-and-me

      # Step 4: Install dependencies and build frontend
      - name: Install and build frontend
        run: |
          cd macro-and-me
          pwd
          npm ci
          npm run build

      - name: Copy frontend build to server
        run: |
          pwd
          cp -r macro-and-me/build server/public

      # Step 5: Deploy to App Engine
      - name: Deploy to App Engine
        run: |
          cd server
          npm ci
          gclou app deploy --quiet
